backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/media'
public_folder: '/images'
locale: fr
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: events
    label: Evénements
    label_singular: Evénement
    folder: content/events
    create: true
    editor: { preview: false }
    filter: {field: "visibleInCms", value: true}
    view_groups:
      - label: Type
        field: kind
    fields:
      - {label: "Visible", name: "visibleInCms", widget: hidden, default: true}
      - { label: Titre, name: title }
      - { label: Type, name: kind, widget: relation, collection: kinds, display_fields: [title], value_field: "{{slug}}", search_fields: [title] }
      - { label: Année, name: year, widget: number, default: 2000, value_type: int, min: 1000, max: 3000, step: 1 }
      - { label: Personnes, name: persons, widget: relation, collection: persons, display_fields: [title], value_field: "{{slug}}", search_fields: [title], multiple: true, min: 0, required: false }
      - { label: Organisations, name: organizations, widget: relation, collection: organizations, display_fields: [title], value_field: "{{slug}}", search_fields: [title], multiple: true, min: 0, required: false }
      - { label: Abstract, name: abstract, required: false, widget: text }
      - { label: Description, name: description, widget: markdown, minimal: true, required: false, buttons: [bold, link], editor_components: [], modes: [rich_text] }
      - { label: Image, name: image, widget: image, media_folder: /assets/images/events, allow_multiple: false, required: false }
      - { label: Galerie, name: gallery, widget: image, media_folder: /assets/images/events, allow_multiple: true, required: false, min: 0 }
      - { label: "Liens vers des ressources", name: resources, required: false, multiple: true, min: 0 }
      - { label: "Lien vers une vidéo", name: video, required: false }
      - { label: "Lien vers un podcast", name: podcast, required: false }

  - name: persons
    label: Personnes
    label_singular: Personne
    folder: content/persons
    create: true
    editor: { preview: false }
    filter: {field: "visibleInCms", value: true}
    fields:
      - {label: "Visible", name: "visibleInCms", widget: hidden, default: true}
      - { label: Nom complet, name: title }
      - { label: Prénom, name: first_name }
      - { label: Nom, name: last_name }
      - { label: Image, name: image, widget: image, media_folder: '/assets/images/persons', allow_multiple: false }
      - { label: Description, name: description, required: false, widget: text }
      - { label: Naissance, name: birth, widget: number, default: 1950, value_type: int, min: -5000, max: 3000, step: 1 }
      - { label: Décès, name: death, widget: number, value_type: int, min: 1000, max: 3000, step: 1, required: false }
  
  - name: organizations
    label: Organisations
    label_singular: Organisation
    folder: content/organizations
    create: true
    editor: { preview: false }
    filter: {field: "visibleInCms", value: true}
    fields:
      - {label: "Visible", name: "visibleInCms", widget: hidden, default: true}
      - { label: Nom, name: title }
      - { label: Image, name: image, widget: image, media_folder: '/assets/images/persons', allow_multiple: false }
      - { label: Description, name: description, required: false, widget: text }
      - { label: Fondation, name: birth, widget: number, default: 1950, value_type: int, min: 1000, max: 3000, step: 1 }
      - { label: Personnes, name: persons, widget: relation, collection: persons, display_fields: [title], value_field: "{{slug}}", search_fields: [title], multiple: true, min: 0, required: false }
  
  - name: kinds
    label: Types
    label_singular: Type
    folder: content/kinds
    create: true
    editor: { preview: false }
    filter: {field: "visibleInCms", value: true}
    fields:
      - {label: "Visible", name: "visibleInCms", widget: hidden, default: true}
      - { label: Titre, name: title }
      - { label: Description, name: description, widget: text, required: false }